---
apiVersion: v1
kind: Secret
metadata:
  name: controller-manager-config
data:
  kubeconfig: ${GARDENER_KUBECONFIG_B64_ENCODED}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: cluster-api-provider-gardener
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - env:
          - name: GARDENER_KUBECONFIG
            value: /etc/gardener/kubeconfig
        command:
        - /manager
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
        image: capga-controller:latest
        imagePullPolicy: IfNotPresent
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
          - name: gardener-kubeconfig
            mountPath: /etc/gardener
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - name: gardener-kubeconfig
          secret:
            secretName: controller-manager-config
